# Generated by Django 3.2.7 on 2021-10-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211017_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='qr_code',
            field=models.URLField(blank=True, null=True),
        ),
    ]
