# Generated by Django 3.2.7 on 2022-06-05 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorhits'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorhits',
            options={'verbose_name_plural': 'Doctor Hits'},
        ),
    ]
