# Generated by Django 3.2.7 on 2021-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicelanguage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='media/thumbnails'),
        ),
    ]
