# Generated by Django 3.2.7 on 2021-10-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_content_video_thumnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='video_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
