# Generated by Django 3.2.7 on 2021-10-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_content_video_embed_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='video_thumnail',
        ),
        migrations.RemoveField(
            model_name='content',
            name='video_url',
        ),
    ]
